### ISSUE TITLE
Provider list breaks upon applying 'Favorite' filter

### ISSUE THREAD

**Issue by valiant1x** [LetheanMovement/lethean-gui#132]
If the user has no favorites configured, the provider list shows debugging content if the user selects 'Favorites' as a filter:

![image](https://user-images.githubusercontent.com/29789261/51628369-77b51180-1f0a-11e9-83d6-45359cfef009.png)

If the user has only one favorite selected, the debugging content is still visible but 'hidden' partially by the single favorite item:

![image](https://user-images.githubusercontent.com/29789261/51628337-64a24180-1f0a-11e9-866e-672685e01e1e.png)

Resolution:
If a user has no favorites, the UI should indicate that.
If a user has only enough favorites to partially cover the debugging content, the debugging content should be hidden.

**Comment by vjirasek** [comment]
Same error happens when selecting TYPE: VPN - and not even touching Favourite.

**Comment by valiant1x** [comment]
fixed in #144
