### ISSUE TITLE
Multiple payments being sent on Mac

### ISSUE THREAD

**Issue by pallas1** [LetheanMovement/lethean-gui#136]
A user experienced an issue with the MacOS wallet, creating multiple payments even though he did not authorize the wallet to continue to run outside of the first few minutes that he paid for.
Issue n.3 reported by ThePigWee.

**Comment by valiant1x** [comment]
Tried replicating the issue on Windows multiple times without success. The logic for sending payments to providers should not vary from one platform to another. At this time I am unable to reproduce the issue.
