### ISSUE TITLE
Provider list does not load after VPN disconnect in Windows VPN alpha GUI wallet

### ISSUE THREAD

**Issue by ronnylov** [LetheanMovement/lethean-gui#165]
As title say when using Lethernet FR VPN Test provider and then disconnect, give a rating and going back to provider list to try another provider the list of providers is empty and it say press filter button to retry. Error Code: 0

Only way I could make provider list to load again was restarting the GUI wallet.

**Comment by valiant1x** [comment]
Fixed in #169
