### ISSUE TITLE
Unable to uncompress wallet zip file on Windows 10 x64.

### ISSUE THREAD

**Issue by mtl1979** [LetheanMovement/lethean-gui#35]
After latest update on fix regarding issue valiant1x/intensecoin#45, Windows 10 is blocking the unzip of wallet archive... I know we should whitelist the directory containing executables, but we can't until it is actually created. Previous versions were not blocked even though most executables and libraries containing word "Monero" were flagged as potentially unwanted programs.

Only workaround currently is to whitelist parent directory where the wallet archive is unzipped or to extract the archive to existing directory that is already whitelisted and allow rewriting matching existing files.

This might also affect other versions of Windows 10 that have Windows Defender enabled. As it is a system service, there is no way to disable it without compromising the whole operating system to malicious infections.

**Comment by iedemam** [comment]
Closing. I haven't seen another independent report of this, nor noticed it internally.

Re-open and @ me if someone can replicate.
