### ISSUE TITLE
Proxy usage time is shorter than what was paid for

### ISSUE THREAD

**Issue by valiant1x** [LetheanMovement/lethean-gui#67]
Many users have reported purchasing, for example, 10 minutes of proxy time yields only 8-9 minutes of connection time. After the shorter amount of time elapses, the user is not able to browse any websites using the browser extension. Reconnecting the browser extension does not make a difference. The 'transferred' label in the wallet tracking UL/DL bandwidth also becomes stuck at the moment the connection becomes dead.

This problem may be exacerbated by the GUI freezing as described in #65, which is pausing the timer and giving a false perception of how much time was used. **The GUI should be measuring time paid for by counting time elapsed since a starting point in time, not only increment the time every 1sec when the timer loop runs.** @alfasoftpt As the GUI appears to only increment the "Time online" label when the timer ticks, it is susceptible to inaccuracies related to GUI lag.

When I run an external stopwatch, the time is accurate as it was paid. The issue appears to be the GUI is not properly counting/displaying "Time online".

The issue does not seem to be entirely GUI related. Sometimes connections will become unresponsive 15+min before time ends - all browser navigation results in timeouts, and all data stops flowing in/out of HAProxy according to the wallet GUI.

**Comment by iedemam** [comment]
The commit referenced here has a lot of curl stuff in it. Has this been resolved with the subsequent switch to boost asio?

**Comment by valiant1x** [comment]
Probably a combination of server and client side issues, but no longer a problem today..
