### ISSUE TITLE
Haproxy status checking timing out during initial payment checking phase

### ISSUE THREAD

**Issue by valiant1x** [LetheanMovement/lethean-gui#70]
Currently only occurring on +linux because Windows is not checking haproxy status codes.

If a payment takes awhile to confirm initially, the GUI gives up on checking the status with haproxy and a user is never connected.

**Comment by iedemam** [comment]
Has this been resolved? A lot of work has gone into this area since Sep 10.

**Comment by pallas1** [comment]
I didn't experience it any more
